### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by bryansippel** [christianjianelli/zrestapi#1]
I tried running ZSAPLINK in SE38 to install the NUGG_ZRESTAPI-1.0.0.nugg file, and I received the following list of messages...
   CLAS ZCL_REST_RESOURCE_HELLO_WORLD
   CLAS ZCL_REST_AUTH
   CLAS ZCL_USW
   CLAS ZCL_USW_UTILS
   CLAS ZCL_REST_HANDLER
   DOMA ZDO_RESTAPI_REFUSRONLY
   DTEL ZPBR_CPFNR
   DTEL ZDE_RESTAPI_REFUSRONLY
   DTEL ZDE_RESTAPI_PRIVATE_KEY
   DTEL ZED_INTERNET_USER_STATUS
   DTEL ZDE_RESTAPI_RESOURCE_ID
   DTEL ZDE_RESTAPI_APP_ID
   INTF ZIF_REST_RESOURCE_READ
   INTF ZIF_REST_RESOURCE_UPDATE
   INTF ZIF_REST_RESOURCE_DELETE
   INTF ZIF_REST_RESOURCE_CREATE
   MSAG ZREST
   PROG ZRUSW01_PAI
   PROG ZRUSW01_PBO
   PROG ZRUSW01_IMP
   PROG ZRUSW01_DEF
   PROG ZRUSW01_TOP
   PROG ZRUSW01
   PROG ZRUSW00_PAI
   PROG ZRUSW00_PBO
   PROG ZRUSW00_IMP
   PROG ZRUSW00_DEF
   PROG ZRUSW00_TOP
   PROG ZRUSW00
   TABL ZTBUSWUA
   TABL ZTBUSWPR
   TABL ZST_ALV_ZRUSW01
   TABL ZSTUSWIU_ALV
   TABL ZSTUSWUA_ALV
   TABL ZSTUSWDU_ALV
   TABL ZST_REST_RESPONSE_BASIC
   TABL ZTBUSWDU
   TABL ZTBUSWIU
   Plugin for object type TRAN is not installed on this system
   Plugin for object type TRAN is not installed on this system

and none of the objects are available in our system.

What happened?

**Comment by christianjianelli** [comment]
The SAPlink plugin for Transactions is missing in your system. You can download it at:

https://code.google.com/archive/p/saplink-plugins-ksq/downloads

File
CLAS_ZSAPLINK_TRANSACTIONS.slnk

SAPlink does not import anything if a plugin is missing. After installing the plugin above you will be able to import the objects in the NUGG_ZRESTAPI-1.0.0.nugg.
